server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3309/demo_db?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      #指服務建立後要用何種方式執行ddl指令
      ddl-auto: update
      # mySQL 8.0
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: "Asia/Hong_Kong"