spring :
  datasource :
    url : jdbc:mysql://localhost:3309/demo_db?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username : root
    password : 1234

  jpa :
    hibernate :
      ddl-auto : update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql : false
    properties :
      hibernate :
        jdbc :
          time_zone : "Asia/Hong_Kong"

  profiles :
    active : dockercompose

#pod.ip
pod :
  machine :
    ip : 127.0.0.1