version: "3.5"

services:

  db:
    image: mysql:8.0
    build:
      context: manifests/db_context
      dockerfile: Dockerfile
    ports:
      - 3315:3309
    container_name: demo_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234

  tomcat:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8091:8080
      - 8012:8000 # debug port
    networks:
      hybris_docker_network:
        ipv4_address: 172.27.0.5
    container_name: demo_tomcat

networks:
  hybris_docker_network:
    ipam:
      driver: default
      config: # fix the internal IP to avoid redis IP warp causing slave not found
        - subnet: 172.27.0.0/16